#!/bin/bash
# Exit with non-zero status if any of the following commands fail
set -e
# Run prettier on staged files only
./node_modules/.bin/prettier --check $(git diff-index --cached --name-only HEAD)
