#!/bin/bash

# Exit with non-zero status if any of the following commands fail
set -e

# Run prettier + shfmt
echo "Styling..." | lolcat
npm --loglevel silent run style:check
shfmt -l .
echo "Files are formatted!" | lolcat
